import { Block, PageSettings } from './types';

export interface PageTemplate {
  id: string;
  name: string;
  description: string;
  thumbnail: string;
  blocks: Block[];
  settings: Partial<PageSettings>;
}

const generateId = () => Math.random().toString(36).substr(2, 9);

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: 'newsletter',
    name: 'Newsletter Signup',
    description: 'Clean newsletter subscription page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'gradient',
      gradientFrom: '#667eea',
      gradientTo: '#764ba2',
      primaryColor: '#667eea',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Stay in the Loop',
          level: 'h1',
          fontSize: 42,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Get the latest updates, tips, and exclusive content delivered straight to your inbox.',
          fontSize: 18,
          alignment: 'center',
          color: '#e0e7ff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'Enter your email',
          buttonText: 'Subscribe Now',
          buttonColor: '#ffffff',
          successMessage: 'Welcome aboard! Check your inbox.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Join 10,000+ subscribers • No spam, ever',
          fontSize: 14,
          alignment: 'center',
          color: '#c4b5fd',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'waitlist',
    name: 'Startup Waitlist',
    description: 'Modern waitlist for product launches',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#0f172a',
      primaryColor: '#06b6d4',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Logo',
          width: 80,
          height: 80,
          alignment: 'center',
          borderRadius: 16,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Something Amazing is Coming',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: "We're building the next generation of productivity tools. Be the first to experience it.",
          fontSize: 20,
          alignment: 'center',
          color: '#94a3b8',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'countdown',
        props: {
          targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          label: 'Launching in',
          showDays: true,
          showHours: true,
          showMinutes: true,
          showSeconds: false,
          color: '#06b6d4',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'Your email',
          buttonText: 'Join the Waitlist',
          buttonColor: '#06b6d4',
          successMessage: "You're on the list! We'll be in touch soon.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
    ],
  },
  {
    id: 'event',
    name: 'Event Registration',
    description: 'Professional event signup page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'gradient',
      gradientFrom: '#f97316',
      gradientTo: '#ea580c',
      primaryColor: '#f97316',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'VIRTUAL EVENT • MARCH 2025',
          fontSize: 14,
          alignment: 'center',
          color: '#fef3c7',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Design Summit 2025',
          level: 'h1',
          fontSize: 52,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Join industry leaders for 3 days of inspiration, learning, and networking.',
          fontSize: 20,
          alignment: 'center',
          color: '#fed7aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: true,
          namePlaceholder: 'Full name',
          emailPlaceholder: 'Work email',
          phonePlaceholder: 'Phone number',
          buttonText: 'Reserve My Spot',
          buttonColor: '#1e293b',
          successMessage: "You're registered! Check your email for details.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Last year\'s summit was incredible. The insights I gained transformed our design process."',
          author: 'Sarah Chen',
          role: 'Head of Design, TechCorp',
          avatar: '',
          backgroundColor: 'rgba(255,255,255,0.1)',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'product_launch',
    name: 'Product Launch',
    description: 'Exciting product reveal page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#18181b',
      primaryColor: '#a855f7',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '✨ NEW RELEASE',
          fontSize: 14,
          alignment: 'center',
          color: '#a855f7',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Meet Your New Favorite App',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'The all-in-one solution for modern teams. Faster, smarter, better.',
          fontSize: 20,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Product Preview',
          width: 400,
          height: 250,
          alignment: 'center',
          borderRadius: 12,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'Enter your email',
          buttonText: 'Get Early Access',
          buttonColor: '#a855f7',
          successMessage: 'Welcome to the future!',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'social',
        props: {
          platforms: [
            { name: 'twitter', url: '#', enabled: true },
            { name: 'linkedin', url: '#', enabled: true },
          ],
          size: 'md',
          color: '#71717a',
          alignment: 'center',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
    ],
  },
  {
    id: 'free_resource',
    name: 'Free Download',
    description: 'Lead magnet download page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'gradient',
      gradientFrom: '#10b981',
      gradientTo: '#059669',
      primaryColor: '#10b981',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'FREE DOWNLOAD',
          fontSize: 14,
          alignment: 'center',
          color: '#a7f3d0',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'The Ultimate Startup Playbook',
          level: 'h1',
          fontSize: 44,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '50+ pages of actionable strategies, templates, and frameworks used by top founders.',
          fontSize: 18,
          alignment: 'center',
          color: '#d1fae5',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Ebook Cover',
          width: 200,
          height: 280,
          alignment: 'center',
          borderRadius: 8,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'Your best email',
          buttonText: 'Download Free Guide',
          buttonColor: '#ffffff',
          successMessage: 'Check your email for the download link!',
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '🔒 Your email is safe with us. No spam.',
          fontSize: 14,
          alignment: 'center',
          color: '#a7f3d0',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'saas_landing',
    name: 'SaaS Landing',
    description: 'Modern SaaS product landing page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#ffffff',
      primaryColor: '#3b82f6',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'SaaSify',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Features', url: '#features' },
            { id: '2', label: 'Pricing', url: '#pricing' },
            { id: '3', label: 'About', url: '#about' },
          ],
          ctaButton: { enabled: true, text: 'Get Started', url: '#signup' },
          style: 'solid',
          alignment: 'spread',
          sticky: true,
          backgroundColor: '#ffffff',
          textColor: '#1e293b',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        props: {
          headline: 'Build Better Products Faster',
          subheadline: 'The all-in-one platform that helps teams ship 10x faster with AI-powered workflows.',
          buttonText: 'Start Free Trial',
          buttonLink: '#signup',
          backgroundImage: '',
          backgroundOverlay: 0,
          height: 'large',
          alignment: 'center',
          textColor: 'dark',
        },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Zap', title: 'Lightning Fast', description: 'Optimized for speed and performance' },
            { id: '2', icon: 'Shield', title: 'Secure by Default', description: 'Enterprise-grade security built in' },
            { id: '3', icon: 'BarChart', title: 'Analytics', description: 'Deep insights into your data' },
            { id: '4', icon: 'Users', title: 'Team Collaboration', description: 'Work together seamlessly' },
          ],
          columns: 4,
          style: 'cards',
          iconColor: '#3b82f6',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'pricing',
        props: {
          tiers: [
            { id: '1', name: 'Free', price: '$0', period: 'month', description: 'For individuals', features: ['1 project', 'Basic analytics', 'Email support'], buttonText: 'Get Started', buttonUrl: '#', highlighted: false },
            { id: '2', name: 'Pro', price: '$49', period: 'month', description: 'For teams', features: ['Unlimited projects', 'Advanced analytics', 'Priority support', 'API access'], buttonText: 'Start Trial', buttonUrl: '#', highlighted: true },
            { id: '3', name: 'Enterprise', price: 'Custom', period: '', description: 'For large orgs', features: ['Everything in Pro', 'SSO', 'Dedicated support', 'Custom integrations'], buttonText: 'Contact Sales', buttonUrl: '#', highlighted: false },
          ],
          columns: 3,
          style: 'cards',
          highlightColor: '#3b82f6',
        },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'SaaSify',
          logoImage: '',
          tagline: 'Building the future of work',
          columns: [
            { id: '1', title: 'Product', links: [{ id: 'a', label: 'Features', url: '#' }, { id: 'b', label: 'Pricing', url: '#' }] },
            { id: '2', title: 'Company', links: [{ id: 'c', label: 'About', url: '#' }, { id: 'd', label: 'Careers', url: '#' }] },
          ],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 SaaSify. All rights reserved.',
          style: 'columns',
          backgroundColor: '#1e293b',
          textColor: '#ffffff',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'agency_portfolio',
    name: 'Agency Portfolio',
    description: 'Creative agency showcase page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#fafafa',
      primaryColor: '#ec4899',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Studio X',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Work', url: '#work' },
            { id: '2', label: 'Services', url: '#services' },
            { id: '3', label: 'Contact', url: '#contact' },
          ],
          ctaButton: { enabled: true, text: 'Hire Us', url: '#contact' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#18181b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'We Craft Digital Experiences',
          level: 'h1',
          fontSize: 64,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#18181b',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Award-winning creative agency specializing in brand identity, web design, and digital marketing.',
          fontSize: 22,
          alignment: 'center',
          color: '#71717a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Palette', title: 'Brand Identity', description: 'Logos, colors, and visual systems' },
            { id: '2', icon: 'Layout', title: 'Web Design', description: 'Beautiful, responsive websites' },
            { id: '3', icon: 'TrendingUp', title: 'Digital Marketing', description: 'Strategies that drive growth' },
          ],
          columns: 3,
          style: 'minimal',
          iconColor: '#ec4899',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Studio X transformed our brand completely. The results exceeded all expectations."',
          author: 'Mike Johnson',
          role: 'Founder, TechStart',
          avatar: '',
          backgroundColor: '#fdf4ff',
        },
      },
      {
        id: generateId(),
        type: 'contact-form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          showMessage: true,
          nameLabel: 'Name',
          emailLabel: 'Email',
          phoneLabel: 'Phone',
          messageLabel: 'Tell us about your project',
          namePlaceholder: 'Your name',
          emailPlaceholder: 'your@email.com',
          phonePlaceholder: '',
          messagePlaceholder: 'Describe your project...',
          buttonText: 'Send Message',
          buttonColor: '#ec4899',
          successMessage: "Thanks! We'll be in touch soon.",
          requirePhone: false,
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'webinar',
    name: 'Webinar Registration',
    description: 'Live event registration page',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'gradient',
      gradientFrom: '#1e3a8a',
      gradientTo: '#7c3aed',
      primaryColor: '#fbbf24',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '🎯 FREE LIVE WEBINAR',
          fontSize: 14,
          alignment: 'center',
          color: '#fbbf24',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Master Growth Marketing in 2025',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Join 500+ marketers learning the exact strategies top brands use to scale.',
          fontSize: 20,
          alignment: 'center',
          color: '#c7d2fe',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'countdown',
        props: {
          targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          label: 'Starts in',
          showDays: true,
          showHours: true,
          showMinutes: true,
          showSeconds: true,
          color: '#fbbf24',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'accordion',
        props: {
          items: [
            { id: '1', question: "What you'll learn", answer: 'Advanced growth tactics, conversion optimization, and retention strategies used by unicorn startups.' },
            { id: '2', question: 'Who should attend', answer: 'Marketing managers, founders, and growth professionals looking to scale their businesses.' },
            { id: '3', question: 'Is there a replay?', answer: 'Yes! All registrants receive a recording within 24 hours.' },
          ],
          allowMultiple: true,
          style: 'bordered',
          iconPosition: 'right',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'Work email',
          buttonText: 'Reserve My Spot',
          buttonColor: '#fbbf24',
          successMessage: "You're registered! Check your email for details.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '✓ Free to attend • ✓ Live Q&A • ✓ Certificate included',
          fontSize: 14,
          alignment: 'center',
          color: '#a5b4fc',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'personal_brand',
    name: 'Personal Brand',
    description: 'Minimalist personal portfolio',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#fef3c7',
      primaryColor: '#f59e0b',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Profile Photo',
          width: 120,
          height: 120,
          alignment: 'center',
          borderRadius: 60,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 24 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Hey, I\'m Alex 👋',
          level: 'h1',
          fontSize: 42,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#78350f',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Product designer & writer helping startups create delightful user experiences.',
          fontSize: 20,
          alignment: 'center',
          color: '#92400e',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'social',
        props: {
          platforms: [
            { name: 'twitter', url: '#', enabled: true },
            { name: 'linkedin', url: '#', enabled: true },
            { name: 'instagram', url: '#', enabled: true },
          ],
          size: 'lg',
          color: '#b45309',
          alignment: 'center',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Get My Weekly Newsletter',
          level: 'h2',
          fontSize: 28,
          fontWeight: 'semibold',
          alignment: 'center',
          color: '#78350f',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Design tips, career advice, and behind-the-scenes of my projects.',
          fontSize: 16,
          alignment: 'center',
          color: '#92400e',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'Enter your email',
          buttonText: 'Subscribe',
          buttonColor: '#f59e0b',
          successMessage: 'Welcome! Check your inbox.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
    ],
  },
];
