import { Block, PageSettings } from './types';

export interface PageTemplate {
  id: string;
  name: string;
  description: string;
  thumbnail: string;
  blocks: Block[];
  settings: Partial<PageSettings>;
  requiredPlan?: 'free' | 'pro' | 'business'; // undefined or 'free' = available to all
}

const generateId = () => Math.random().toString(36).substr(2, 9);

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: 'newsletter',
    name: 'Newsletter Signup',
    description: 'Premium newsletter with social proof and feature highlights',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      primaryColor: '#8b5cf6',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'The Brief',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'About', url: '#about' },
            { id: '2', label: 'Archives', url: '#archives' },
          ],
          ctaButton: { enabled: true, text: 'Subscribe', url: '#signup' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '✦ TRUSTED BY 25,000+ READERS',
          fontSize: 13,
          alignment: 'center',
          color: '#8b5cf6',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'The newsletter for people who build the future',
          level: 'h1',
          fontSize: 56,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Weekly insights on technology, design, and strategy. Curated for founders, creators, and operators who ship.',
          fontSize: 20,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'you@company.com',
          buttonText: 'Subscribe — It\'s Free',
          buttonColor: '#8b5cf6',
          successMessage: 'Welcome aboard! Check your inbox.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=400&fit=crop',
          alt: 'Newsletter preview - replace with your own image',
          width: 600,
          height: 300,
          alignment: 'center',
          borderRadius: 12,
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'No spam. Unsubscribe anytime. Read by teams at Stripe, Notion & Linear.',
          fontSize: 13,
          alignment: 'center',
          color: '#71717a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: {
          style: 'solid',
          color: '#27272a',
          width: 100,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What you\'ll get every week',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Zap', title: 'Trend Analysis', description: 'Deep dives into emerging tech and market shifts before they go mainstream' },
            { id: '2', icon: 'BookOpen', title: 'Curated Reads', description: 'The 5 most important articles you need to read, distilled into key takeaways' },
            { id: '3', icon: 'Target', title: 'Actionable Playbooks', description: 'Step-by-step frameworks you can apply to your business immediately' },
          ],
          columns: 3,
          style: 'cards',
          iconColor: '#8b5cf6',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"The Brief is the only newsletter I actually open every week. It\'s become essential to how I think about strategy."',
          author: 'Sarah Lin',
          role: 'VP Product, Acme Inc.',
          avatar: '',
          backgroundColor: '#18181b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'The Brief',
          logoImage: '',
          tagline: 'Insights for builders.',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 The Brief. All rights reserved.',
          style: 'minimal',
          backgroundColor: '#0a0a0a',
          textColor: '#71717a',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'waitlist',
    name: 'Startup Waitlist',
    description: 'High-converting waitlist with countdown and social proof',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#020617',
      primaryColor: '#06b6d4',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Nexus AI',
          logoImage: '',
          menuItems: [],
          ctaButton: { enabled: false, text: '', url: '' },
          style: 'transparent',
          alignment: 'center',
          sticky: false,
          backgroundColor: 'transparent',
          textColor: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '🚀 LAUNCHING SOON — JOIN 8,400+ ON THE LIST',
          fontSize: 13,
          alignment: 'center',
          color: '#06b6d4',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'The AI workspace that replaces 5 tools',
          level: 'h1',
          fontSize: 54,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'One intelligent platform for docs, tasks, communications, analytics, and automation. Built for teams that move fast.',
          fontSize: 20,
          alignment: 'center',
          color: '#94a3b8',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'countdown',
        props: {
          targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          label: 'Early access opens in',
          showDays: true,
          showHours: true,
          showMinutes: true,
          showSeconds: true,
          color: '#06b6d4',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          buttonText: 'Join the Waitlist →',
          buttonColor: '#06b6d4',
          successMessage: "You're in! We'll notify you at launch.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
          alt: 'Product mockup - replace with your own screenshot',
          width: 700,
          height: 400,
          alignment: 'center',
          borderRadius: 16,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Why teams are switching',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Brain', title: 'AI-First Design', description: 'Every feature is powered by contextual AI that learns your workflow' },
            { id: '2', icon: 'Zap', title: '10x Faster', description: 'Automate repetitive tasks and focus on what matters' },
            { id: '3', icon: 'Lock', title: 'Enterprise Security', description: 'SOC 2 Type II, SSO, audit logs, and data encryption at rest' },
            { id: '4', icon: 'Globe', title: 'Works Everywhere', description: 'Desktop, mobile, API — seamlessly synced across all devices' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#06b6d4',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"We tested the beta and immediately replaced Slack, Notion, and Asana. This is the future of team collaboration."',
          author: 'James Park',
          role: 'CTO, Velocity Labs',
          avatar: '',
          backgroundColor: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Nexus AI',
          logoImage: '',
          tagline: 'The future of teamwork.',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Nexus AI Inc.',
          style: 'minimal',
          backgroundColor: '#020617',
          textColor: '#64748b',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'event',
    name: 'Event Registration',
    description: 'Conference-grade event page with speakers and agenda',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#0c0a09',
      primaryColor: '#f97316',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'SUMMIT \'26',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Speakers', url: '#speakers' },
            { id: '2', label: 'Agenda', url: '#agenda' },
            { id: '3', label: 'FAQ', url: '#faq' },
          ],
          ctaButton: { enabled: true, text: 'Register Free', url: '#register' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        props: {
          headline: 'Design & Dev Summit 2026',
          subheadline: '3 days of world-class talks, hands-on workshops, and networking with 2,000+ creators. March 15–17, San Francisco.',
          buttonText: 'Get Your Free Ticket →',
          buttonLink: '#register',
          backgroundImage: '',
          backgroundOverlay: 0,
          height: 'large',
          alignment: 'center',
          textColor: 'light',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Mic', title: '30+ Speakers', description: 'Industry leaders from Google, Figma, Vercel, and more' },
            { id: '2', icon: 'Users', title: '2,000 Attendees', description: 'Connect with designers, developers, and founders' },
            { id: '3', icon: 'Lightbulb', title: '15 Workshops', description: 'Hands-on sessions to level up your craft' },
            { id: '4', icon: 'Trophy', title: 'Startup Pitch', description: '$50K in prizes for the best new product' },
          ],
          columns: 4,
          style: 'cards',
          iconColor: '#f97316',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What attendees are saying',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"This summit completely changed how I approach product design. The workshops alone were worth the trip."',
          author: 'Maria Santos',
          role: 'Design Lead, Spotify',
          avatar: '',
          backgroundColor: '#1c1917',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'accordion',
        props: {
          items: [
            { id: '1', question: 'Is the event free?', answer: 'Yes! General admission is completely free. VIP passes with exclusive workshop access are $199.' },
            { id: '2', question: 'Will talks be recorded?', answer: 'All main stage talks will be recorded and available to registered attendees within 48 hours.' },
            { id: '3', question: 'What\'s included?', answer: 'All talks, networking events, lunch, swag bag, and access to the expo hall. VIP includes workshops and private dinner.' },
          ],
          allowMultiple: true,
          style: 'bordered',
          iconPosition: 'right',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Secure your spot',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 10 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Full name',
          emailPlaceholder: 'Work email',
          buttonText: 'Register Now — Free',
          buttonColor: '#f97316',
          successMessage: "You're registered! Check your email for your ticket.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'SUMMIT \'26',
          logoImage: '',
          tagline: 'San Francisco • March 15–17, 2026',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'instagram', url: '#', enabled: true },
          ],
          copyrightText: '© 2026 Summit Conference.',
          style: 'minimal',
          backgroundColor: '#0c0a09',
          textColor: '#78716c',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'product_launch',
    name: 'Product Launch',
    description: 'Premium product reveal with features and early access',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#09090b',
      primaryColor: '#a855f7',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Arc Studio',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Features', url: '#features' },
            { id: '2', label: 'Pricing', url: '#pricing' },
          ],
          ctaButton: { enabled: true, text: 'Get Early Access', url: '#signup' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        props: {
          headline: 'Design tools, reimagined for speed',
          subheadline: 'Arc Studio is a next-generation creative suite that\'s 10x faster than anything you\'ve used. Built with AI at the core.',
          buttonText: 'Request Early Access',
          buttonLink: '#signup',
          backgroundImage: '',
          backgroundOverlay: 0,
          height: 'large',
          alignment: 'center',
          textColor: 'light',
        },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
          alt: 'Product screenshot - replace with your own',
          width: 700,
          height: 400,
          alignment: 'center',
          borderRadius: 16,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'video',
        props: {
          url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          autoplay: false,
          showControls: true,
          aspectRatio: '16:9',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Sparkles', title: 'AI-Powered Editing', description: 'Generate, edit, and refine designs with natural language commands' },
            { id: '2', icon: 'Layers', title: 'Infinite Canvas', description: 'Work on projects of any size with zero performance lag' },
            { id: '3', icon: 'Paintbrush', title: 'Smart Styles', description: 'Automatically generate consistent design systems from your brand' },
            { id: '4', icon: 'Share2', title: 'Real-time Collab', description: 'Work together with your team as if you\'re in the same room' },
            { id: '5', icon: 'Code', title: 'Dev Handoff', description: 'Export production-ready code with one click' },
            { id: '6', icon: 'Smartphone', title: 'Responsive Preview', description: 'See your designs on every device instantly' },
          ],
          columns: 3,
          style: 'cards',
          iconColor: '#a855f7',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'pricing',
        props: {
          tiers: [
            { id: '1', name: 'Starter', price: '$0', period: 'month', description: 'For individual creators', features: ['3 projects', 'AI editing (50/mo)', 'Basic export', 'Community support'], buttonText: 'Start Free', buttonUrl: '#', highlighted: false },
            { id: '2', name: 'Pro', price: '$19', period: 'month', description: 'For professionals', features: ['Unlimited projects', 'Unlimited AI editing', 'Dev handoff', 'Priority support', 'Custom fonts'], buttonText: 'Get Pro', buttonUrl: '#', highlighted: true },
            { id: '3', name: 'Team', price: '$49', period: 'month', description: 'For teams of all sizes', features: ['Everything in Pro', 'Team workspaces', 'Version history', 'SSO & admin', 'Dedicated CSM'], buttonText: 'Contact Sales', buttonUrl: '#', highlighted: false },
          ],
          columns: 3,
          style: 'cards',
          highlightColor: '#a855f7',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Arc Studio cut our design-to-development time by 70%. The AI features are genuinely game-changing."',
          author: 'David Kim',
          role: 'Head of Design, Figma Alumni',
          avatar: '',
          backgroundColor: '#18181b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Be the first to try it',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Early access members get 6 months free on any plan.',
          fontSize: 18,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'Enter your email',
          buttonText: 'Get Early Access →',
          buttonColor: '#a855f7',
          successMessage: 'Welcome! You\'re on the list.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Arc Studio',
          logoImage: '',
          tagline: 'Design at the speed of thought.',
          columns: [
            { id: '1', title: 'Product', links: [{ id: 'a', label: 'Features', url: '#' }, { id: 'b', label: 'Pricing', url: '#' }, { id: 'c', label: 'Changelog', url: '#' }] },
            { id: '2', title: 'Company', links: [{ id: 'd', label: 'About', url: '#' }, { id: 'e', label: 'Blog', url: '#' }, { id: 'f', label: 'Careers', url: '#' }] },
          ],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
            { platform: 'github', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Arc Studio. All rights reserved.',
          style: 'columns',
          backgroundColor: '#09090b',
          textColor: '#71717a',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'free_resource',
    name: 'Free Download',
    description: 'High-converting lead magnet with benefits and trust signals',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#022c22',
      primaryColor: '#10b981',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '📥 FREE GUIDE — 12,000+ DOWNLOADS',
          fontSize: 13,
          alignment: 'center',
          color: '#34d399',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'The 2026 Startup Growth Playbook',
          level: 'h1',
          fontSize: 52,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '87 pages of battle-tested frameworks, templates, and strategies used by YC-backed founders to go from 0 to $1M ARR.',
          fontSize: 20,
          alignment: 'center',
          color: '#a7f3d0',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          buttonText: 'Download Free Playbook →',
          buttonColor: '#10b981',
          successMessage: 'Check your email — the playbook is on its way!',
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#064e3b', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What\'s inside',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Rocket', title: 'Launch Checklist', description: 'A step-by-step pre-launch framework used by 500+ startups' },
            { id: '2', icon: 'Target', title: 'Growth Playbooks', description: 'Exact acquisition channels and tactics with real budget numbers' },
            { id: '3', icon: 'FileText', title: 'Email Templates', description: '20+ cold email and outreach templates with 40%+ reply rates' },
            { id: '4', icon: 'TrendingUp', title: 'Metrics Dashboard', description: 'The exact KPIs and benchmarks for each growth stage' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#10b981',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"This playbook saved us 6 months of trial and error. We hit $500K ARR in 8 months using the frameworks inside."',
          author: 'Priya Mehta',
          role: 'Founder, LaunchPad',
          avatar: '',
          backgroundColor: '#064e3b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '🔒 No spam. Instant download. Trusted by founders at Y Combinator, Techstars & 500 Global.',
          fontSize: 14,
          alignment: 'center',
          color: '#6ee7b7',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'saas_landing',
    name: 'SaaS Landing',
    description: 'Full-featured SaaS landing page with pricing and social proof',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#ffffff',
      primaryColor: '#4f46e5',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Flowbase',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Features', url: '#features' },
            { id: '2', label: 'Pricing', url: '#pricing' },
            { id: '3', label: 'Testimonials', url: '#testimonials' },
            { id: '4', label: 'FAQ', url: '#faq' },
          ],
          ctaButton: { enabled: true, text: 'Start Free →', url: '#signup' },
          style: 'solid',
          alignment: 'spread',
          sticky: true,
          backgroundColor: '#ffffff',
          textColor: '#1e293b',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        props: {
          headline: 'Ship products 10x faster with AI workflows',
          subheadline: 'Flowbase combines project management, design, and development into one AI-powered platform. Trusted by 5,000+ teams worldwide.',
          buttonText: 'Start Free — No Credit Card',
          buttonLink: '#signup',
          backgroundImage: '',
          backgroundOverlay: 0,
          height: 'large',
          alignment: 'center',
          textColor: 'dark',
        },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&h=450&fit=crop',
          alt: 'Dashboard preview - replace with your product screenshot',
          width: 700,
          height: 400,
          alignment: 'center',
          borderRadius: 16,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Everything you need to build faster',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'One platform to replace your entire stack. No more tool fatigue.',
          fontSize: 18,
          alignment: 'center',
          color: '#64748b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Wand2', title: 'AI Copilot', description: 'Generate specs, code, and designs from plain English prompts' },
            { id: '2', icon: 'GitBranch', title: 'Version Control', description: 'Built-in branching and merge workflows for every project' },
            { id: '3', icon: 'BarChart3', title: 'Real-time Analytics', description: 'Track velocity, blockers, and team performance live' },
            { id: '4', icon: 'Plug', title: '100+ Integrations', description: 'Connect with Figma, GitHub, Slack, Jira, and more' },
            { id: '5', icon: 'Shield', title: 'Enterprise Security', description: 'SOC 2, GDPR, SSO, and role-based access controls' },
            { id: '6', icon: 'Headphones', title: '24/7 Support', description: 'Dedicated success managers and <2h response time' },
          ],
          columns: 3,
          style: 'cards',
          iconColor: '#4f46e5',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#e2e8f0', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Simple, transparent pricing',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Start free, scale as you grow. No hidden fees.',
          fontSize: 18,
          alignment: 'center',
          color: '#64748b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'pricing',
        props: {
          tiers: [
            { id: '1', name: 'Starter', price: '$0', period: 'month', description: 'For side projects', features: ['2 projects', 'Basic AI (50 prompts/mo)', 'Community support', '1 GB storage'], buttonText: 'Get Started', buttonUrl: '#', highlighted: false },
            { id: '2', name: 'Pro', price: '$29', period: 'month', description: 'For growing teams', features: ['Unlimited projects', 'Unlimited AI', 'Priority support', '100 GB storage', 'Advanced analytics', 'API access'], buttonText: 'Start Free Trial', buttonUrl: '#', highlighted: true },
            { id: '3', name: 'Enterprise', price: 'Custom', period: '', description: 'For large organizations', features: ['Everything in Pro', 'SSO & SCIM', 'Dedicated CSM', 'Custom SLA', 'On-premise option', 'Audit logs'], buttonText: 'Talk to Sales', buttonUrl: '#', highlighted: false },
          ],
          columns: 3,
          style: 'cards',
          highlightColor: '#4f46e5',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Loved by teams everywhere',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Flowbase replaced 4 tools for us and saved $2,000/month. Our team ships twice as fast now."',
          author: 'Elena Torres',
          role: 'VP Engineering, ScaleUp',
          avatar: '',
          backgroundColor: '#f8fafc',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'accordion',
        props: {
          items: [
            { id: '1', question: 'How does the free plan work?', answer: 'The free plan includes 2 projects with basic AI features. No credit card required. Upgrade anytime.' },
            { id: '2', question: 'Can I cancel my subscription?', answer: 'Yes, cancel anytime with one click. No lock-in contracts. Your data is always exportable.' },
            { id: '3', question: 'Do you offer a free trial?', answer: 'Yes! Pro plan comes with a 14-day free trial with full features. No credit card needed to start.' },
            { id: '4', question: 'What integrations do you support?', answer: 'We integrate with 100+ tools including Figma, GitHub, Slack, Jira, Linear, Notion, and more. Custom webhooks available on Pro.' },
          ],
          allowMultiple: true,
          style: 'bordered',
          iconPosition: 'right',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Ready to build faster?',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 10 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'Work email',
          buttonText: 'Start Free — No Credit Card',
          buttonColor: '#4f46e5',
          successMessage: 'Welcome! Check your email to get started.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Flowbase',
          logoImage: '',
          tagline: 'Ship products 10x faster.',
          columns: [
            { id: '1', title: 'Product', links: [{ id: 'a', label: 'Features', url: '#' }, { id: 'b', label: 'Pricing', url: '#' }, { id: 'c', label: 'Integrations', url: '#' }, { id: 'd', label: 'Changelog', url: '#' }] },
            { id: '2', title: 'Company', links: [{ id: 'e', label: 'About', url: '#' }, { id: 'f', label: 'Blog', url: '#' }, { id: 'g', label: 'Careers', url: '#' }, { id: 'h', label: 'Press', url: '#' }] },
            { id: '3', title: 'Resources', links: [{ id: 'i', label: 'Documentation', url: '#' }, { id: 'j', label: 'Help Center', url: '#' }, { id: 'k', label: 'Community', url: '#' }, { id: 'l', label: 'Status', url: '#' }] },
          ],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
            { platform: 'github', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Flowbase Inc. All rights reserved.',
          style: 'columns',
          backgroundColor: '#0f172a',
          textColor: '#94a3b8',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'agency_portfolio',
    name: 'Agency Portfolio',
    description: 'Minimalist agency showcase with contact form and case studies',
    thumbnail: '/placeholder.svg',
    requiredPlan: 'pro',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#fafafa',
      primaryColor: '#e11d48',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'STUDIO NOIR',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Work', url: '#work' },
            { id: '2', label: 'Services', url: '#services' },
            { id: '3', label: 'About', url: '#about' },
          ],
          ctaButton: { enabled: true, text: 'Start a Project', url: '#contact' },
          style: 'solid',
          alignment: 'spread',
          sticky: true,
          backgroundColor: '#fafafa',
          textColor: '#09090b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'DESIGN · BRAND · DIGITAL',
          fontSize: 13,
          alignment: 'center',
          color: '#e11d48',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'We build brands that people remember',
          level: 'h1',
          fontSize: 60,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#09090b',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Award-winning creative studio specializing in brand identity, digital experiences, and growth strategies for ambitious companies.',
          fontSize: 20,
          alignment: 'center',
          color: '#71717a',
        },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800&h=400&fit=crop',
          alt: 'Agency showcase - replace with your work',
          width: 700,
          height: 350,
          alignment: 'center',
          borderRadius: 12,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Palette', title: 'Brand Identity', description: 'Logo, visual systems, brand guidelines, and packaging that tell your story' },
            { id: '2', icon: 'Monitor', title: 'Web & Digital', description: 'Conversion-focused websites, apps, and digital products that perform' },
            { id: '3', icon: 'TrendingUp', title: 'Growth Strategy', description: 'Data-driven marketing, SEO, and content strategies that drive results' },
          ],
          columns: 3,
          style: 'minimal',
          iconColor: '#e11d48',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#e4e4e7', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What our clients say',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#09090b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Studio Noir didn\'t just redesign our brand — they transformed how customers perceive us. Revenue up 240% since relaunch."',
          author: 'Ryan Fletcher',
          role: 'CEO, Meridian Health',
          avatar: '',
          backgroundColor: '#fff1f2',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Let\'s create something extraordinary',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#09090b',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Tell us about your project and we\'ll get back to you within 24 hours.',
          fontSize: 18,
          alignment: 'center',
          color: '#71717a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'contact-form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          showMessage: true,
          nameLabel: 'Name',
          emailLabel: 'Email',
          phoneLabel: 'Phone',
          messageLabel: 'Project details',
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          phonePlaceholder: '',
          messagePlaceholder: 'Tell us about your project, budget, and timeline...',
          buttonText: 'Send Inquiry →',
          buttonColor: '#e11d48',
          successMessage: "Thanks! We'll be in touch within 24 hours.",
          requirePhone: false,
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'STUDIO NOIR',
          logoImage: '',
          tagline: 'Crafting brands since 2018.',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'instagram', url: '#', enabled: true },
            { platform: 'dribbble', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Studio Noir. All rights reserved.',
          style: 'minimal',
          backgroundColor: '#09090b',
          textColor: '#a1a1aa',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'webinar',
    name: 'Webinar Registration',
    description: 'Professional webinar page with speakers, agenda, and countdown',
    thumbnail: '/placeholder.svg',
    requiredPlan: 'pro',
    settings: {
      backgroundType: 'gradient',
      gradientFrom: '#0f172a',
      gradientTo: '#1e1b4b',
      primaryColor: '#f59e0b',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '🔴 LIVE WEBINAR — LIMITED SEATS',
          fontSize: 13,
          alignment: 'center',
          color: '#f59e0b',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'The AI Revenue Playbook: From $0 to $1M ARR',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Learn the exact AI-powered strategies that 50+ SaaS founders used to hit $1M ARR in under 12 months. Live Q&A included.',
          fontSize: 20,
          alignment: 'center',
          color: '#cbd5e1',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'countdown',
        props: {
          targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          label: 'Going live in',
          showDays: true,
          showHours: true,
          showMinutes: true,
          showSeconds: true,
          color: '#f59e0b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'Work email',
          buttonText: 'Reserve My Free Seat →',
          buttonColor: '#f59e0b',
          successMessage: "You're in! Check your email for the calendar invite.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#334155', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What you\'ll learn',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Brain', title: 'AI-First GTM', description: 'How to build AI-powered go-to-market motions that scale automatically' },
            { id: '2', icon: 'DollarSign', title: 'Revenue Systems', description: 'The exact funnel architecture used by top-performing SaaS companies' },
            { id: '3', icon: 'Users', title: 'Team Scaling', description: 'When and how to hire your first 10 employees for maximum impact' },
            { id: '4', icon: 'Repeat', title: 'Retention Loops', description: 'Product-led retention strategies that reduce churn by 60%' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#f59e0b',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'accordion',
        props: {
          items: [
            { id: '1', question: 'Who is this webinar for?', answer: 'SaaS founders, growth marketers, and operators looking to accelerate revenue using AI-powered strategies.' },
            { id: '2', question: 'Will there be a replay?', answer: 'Yes! All registered attendees receive the full recording and slide deck within 24 hours.' },
            { id: '3', question: 'Is this really free?', answer: 'Yes, completely free. We believe in providing value upfront. No upsells during the webinar.' },
            { id: '4', question: 'How long is the session?', answer: '60 minutes of content + 30 minutes of live Q&A. Come with your questions!' },
          ],
          allowMultiple: true,
          style: 'bordered',
          iconPosition: 'right',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"This webinar gave me the exact playbook I needed. We implemented the AI sales system and 3x\'d our pipeline in 60 days."',
          author: 'Alex Rodriguez',
          role: 'Founder, SalesTech AI',
          avatar: '',
          backgroundColor: '#1e293b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '✓ 100% Free · ✓ Live Q&A · ✓ Replay Included · ✓ Actionable Frameworks',
          fontSize: 14,
          alignment: 'center',
          color: '#94a3b8',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
    ],
  },
  {
    id: 'personal_brand',
    name: 'Personal Brand',
    description: 'Creator portfolio with bio, links, and newsletter signup',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#0a0a0a',
      primaryColor: '#f59e0b',
    },
    blocks: [
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Profile Photo',
          width: 120,
          height: 120,
          alignment: 'center',
          borderRadius: 60,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 24 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Alex Rivera',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Product designer & writer. Building beautiful digital experiences. Previously at Stripe, now independent.',
          fontSize: 20,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'social',
        props: {
          platforms: [
            { name: 'twitter', url: '#', enabled: true },
            { name: 'linkedin', url: '#', enabled: true },
            { name: 'instagram', url: '#', enabled: true },
            { name: 'github', url: '#', enabled: true },
          ],
          size: 'lg',
          color: '#f59e0b',
          alignment: 'center',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#27272a', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'What I do',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Paintbrush', title: 'Design Consulting', description: 'Help startups create world-class products and design systems' },
            { id: '2', icon: 'BookOpen', title: 'Writing', description: 'Weekly essays on design, creativity, and building in public' },
            { id: '3', icon: 'Mic', title: 'Speaking', description: 'Keynotes and workshops at conferences worldwide' },
          ],
          columns: 3,
          style: 'cards',
          iconColor: '#f59e0b',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Alex\'s design thinking workshop was the most impactful session at our company retreat. Highly recommend."',
          author: 'Nina Patel',
          role: 'CPO, Ramp',
          avatar: '',
          backgroundColor: '#18181b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 50 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Get my weekly newsletter',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'semibold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Design insights, career reflections, and behind-the-scenes of my projects. Read by 8,000+ creators.',
          fontSize: 18,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: false,
          showEmail: true,
          showPhone: false,
          emailPlaceholder: 'you@email.com',
          buttonText: 'Subscribe →',
          buttonColor: '#f59e0b',
          successMessage: 'Welcome! Check your inbox.',
          layout: 'inline',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 30 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Alex Rivera',
          logoImage: '',
          tagline: 'Designing the future, one pixel at a time.',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Alex Rivera.',
          style: 'minimal',
          backgroundColor: '#0a0a0a',
          textColor: '#52525b',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    description: 'Showcase your best work with a clean, visual portfolio layout',
    thumbnail: '/placeholder.svg',
    requiredPlan: 'pro',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#111111',
      primaryColor: '#22d3ee',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'FOLIO.',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Work', url: '#work' },
            { id: '2', label: 'About', url: '#about' },
            { id: '3', label: 'Contact', url: '#contact' },
          ],
          ctaButton: { enabled: true, text: 'Hire Me', url: '#contact' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 80 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'DESIGNER · DEVELOPER · CREATOR',
          fontSize: 13,
          alignment: 'center',
          color: '#22d3ee',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'I craft digital experiences that leave an impression',
          level: 'h1',
          fontSize: 56,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Full-stack designer with 8+ years of experience building products for startups and Fortune 500 companies.',
          fontSize: 20,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Selected Work',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Smartphone', title: 'FinFlow App', description: 'Mobile banking redesign that increased daily active users by 180%' },
            { id: '2', icon: 'Globe', title: 'Meridian Web', description: 'E-commerce platform generating $4M+ in annual revenue' },
            { id: '3', icon: 'Palette', title: 'Aura Brand', description: 'Complete brand identity system for a Series A health-tech startup' },
            { id: '4', icon: 'Monitor', title: 'CloudBase Dashboard', description: 'Analytics dashboard serving 10,000+ daily enterprise users' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#22d3ee',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'stats',
        props: {
          stats: [
            { id: '1', value: '50+', label: 'Projects Shipped' },
            { id: '2', value: '8', label: 'Years Experience' },
            { id: '3', value: '30+', label: 'Happy Clients' },
            { id: '4', value: '5', label: 'Awards Won' },
          ],
          columns: 4,
          style: 'cards',
          valueColor: '#22d3ee',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"An exceptional designer who truly understands product thinking. The results speak for themselves."',
          author: 'Michael Chen',
          role: 'CEO, FinFlow',
          avatar: '',
          backgroundColor: '#1a1a1a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: "Let's work together",
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#ffffff',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Available for freelance projects and full-time opportunities.',
          fontSize: 18,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'contact-form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          showMessage: true,
          nameLabel: 'Name',
          emailLabel: 'Email',
          phoneLabel: 'Phone',
          messageLabel: 'Tell me about your project',
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          phonePlaceholder: '',
          messagePlaceholder: 'Describe your project, timeline, and budget...',
          buttonText: "Let's Talk →",
          buttonColor: '#22d3ee',
          successMessage: "Thanks! I'll get back to you within 24 hours.",
          requirePhone: false,
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'FOLIO.',
          logoImage: '',
          tagline: 'Crafting digital experiences.',
          columns: [],
          socials: [
            { platform: 'twitter', url: '#', enabled: true },
            { platform: 'linkedin', url: '#', enabled: true },
            { platform: 'dribbble', url: '#', enabled: true },
            { platform: 'github', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 All rights reserved.',
          style: 'minimal',
          backgroundColor: '#111111',
          textColor: '#71717a',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'cv_resume',
    name: 'CV / Resume',
    description: 'Professional resume page with experience, skills, and education',
    thumbnail: '/placeholder.svg',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#ffffff',
      primaryColor: '#2563eb',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Jane Doe',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Experience', url: '#experience' },
            { id: '2', label: 'Skills', url: '#skills' },
            { id: '3', label: 'Education', url: '#education' },
          ],
          ctaButton: { enabled: true, text: 'Download CV', url: '#' },
          style: 'solid',
          alignment: 'spread',
          sticky: true,
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: '',
          alt: 'Profile Photo',
          width: 140,
          height: 140,
          alignment: 'center',
          borderRadius: 70,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Jane Doe',
          level: 'h1',
          fontSize: 48,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Senior Software Engineer · Full-Stack Developer',
          fontSize: 20,
          alignment: 'center',
          color: '#2563eb',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Passionate engineer with 10+ years of experience building scalable web applications. Proficient in React, Node.js, Python, and cloud architecture. Based in San Francisco, CA.',
          fontSize: 16,
          alignment: 'center',
          color: '#64748b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'social',
        props: {
          platforms: [
            { name: 'linkedin', url: '#', enabled: true },
            { name: 'github', url: '#', enabled: true },
            { name: 'twitter', url: '#', enabled: true },
          ],
          size: 'md',
          color: '#2563eb',
          alignment: 'center',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#e2e8f0', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Work Experience',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'left',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 16 },
      },
      {
        id: generateId(),
        type: 'list',
        props: {
          items: [
            { id: '1', text: 'Senior Software Engineer — Google (2021–Present): Led a team of 8 engineers, shipped 3 major product features serving 50M+ users' },
            { id: '2', text: 'Software Engineer — Stripe (2018–2021): Built payment processing APIs handling $10B+ in transactions annually' },
            { id: '3', text: 'Frontend Developer — Airbnb (2015–2018): Redesigned the booking flow, improving conversion rate by 23%' },
          ],
          style: 'bullet',
          fontSize: 15,
          color: '#374151',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Skills & Expertise',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'left',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 16 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Code', title: 'Frontend', description: 'React, TypeScript, Next.js, Tailwind CSS, GraphQL' },
            { id: '2', icon: 'Server', title: 'Backend', description: 'Node.js, Python, Go, PostgreSQL, Redis, Docker' },
            { id: '3', icon: 'Cloud', title: 'Cloud & DevOps', description: 'AWS, GCP, Kubernetes, CI/CD, Terraform' },
            { id: '4', icon: 'Users', title: 'Leadership', description: 'Team management, Agile/Scrum, mentoring, code reviews' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#2563eb',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'divider',
        props: { style: 'solid', color: '#e2e8f0', width: 100 },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Education',
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'left',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 16 },
      },
      {
        id: generateId(),
        type: 'list',
        props: {
          items: [
            { id: '1', text: 'M.S. Computer Science — Stanford University (2015)' },
            { id: '2', text: 'B.S. Computer Engineering — MIT (2013)' },
          ],
          style: 'bullet',
          fontSize: 15,
          color: '#374151',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: "Get in Touch",
          level: 'h2',
          fontSize: 32,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#0f172a',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: "Open to new opportunities. Let's connect!",
          fontSize: 18,
          alignment: 'center',
          color: '#64748b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 16 },
      },
      {
        id: generateId(),
        type: 'form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: false,
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          buttonText: 'Send Message →',
          buttonColor: '#2563eb',
          successMessage: "Thanks for reaching out! I'll respond within 48 hours.",
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Jane Doe',
          logoImage: '',
          tagline: 'Building the future, one line of code at a time.',
          columns: [],
          socials: [
            { platform: 'linkedin', url: '#', enabled: true },
            { platform: 'github', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Jane Doe.',
          style: 'minimal',
          backgroundColor: '#f8fafc',
          textColor: '#94a3b8',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'coaching',
    name: 'Coaching / Consulting',
    description: 'Professional coaching page with services, testimonials, and booking',
    thumbnail: '/placeholder.svg',
    requiredPlan: 'business',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#fdf4ff',
      primaryColor: '#a855f7',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'Coach Kim',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Services', url: '#services' },
            { id: '2', label: 'About', url: '#about' },
            { id: '3', label: 'Testimonials', url: '#testimonials' },
          ],
          ctaButton: { enabled: true, text: 'Book a Call', url: '#book' },
          style: 'solid',
          alignment: 'spread',
          sticky: true,
          backgroundColor: '#fdf4ff',
          textColor: '#1e1b4b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: '✨ EXECUTIVE COACHING & LEADERSHIP DEVELOPMENT',
          fontSize: 13,
          alignment: 'center',
          color: '#a855f7',
        },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Unlock your full potential as a leader',
          level: 'h1',
          fontSize: 52,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#1e1b4b',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: "I help executives and founders break through plateaus, build high-performing teams, and lead with clarity and confidence.",
          fontSize: 20,
          alignment: 'center',
          color: '#6b7280',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'stats',
        props: {
          stats: [
            { id: '1', value: '500+', label: 'Clients Coached' },
            { id: '2', value: '15', label: 'Years Experience' },
            { id: '3', value: '98%', label: 'Satisfaction Rate' },
            { id: '4', value: '40+', label: 'Companies Served' },
          ],
          columns: 4,
          style: 'minimal',
          valueColor: '#a855f7',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'How I Can Help You',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#1e1b4b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'pricing',
        props: {
          tiers: [
            { id: '1', name: 'Discovery Call', price: 'Free', period: '', description: '30-minute introductory session', features: ['Goal assessment', 'Coaching fit evaluation', 'Personalized recommendations', 'No commitment'], buttonText: 'Book Free Call', buttonUrl: '#book', highlighted: false },
            { id: '2', name: '1:1 Coaching', price: '$299', period: 'session', description: 'Deep-dive executive coaching', features: ['90-min sessions', 'Custom action plans', 'Between-session support', 'Resource library access', 'Progress tracking'], buttonText: 'Get Started', buttonUrl: '#book', highlighted: true },
            { id: '3', name: 'Team Package', price: '$2,499', period: 'month', description: 'Leadership team development', features: ['4 team sessions/month', 'Individual coaching', 'Team assessments', 'Workshop facilitation', 'Quarterly reviews'], buttonText: 'Contact Me', buttonUrl: '#book', highlighted: false },
          ],
          columns: 3,
          style: 'cards',
          highlightColor: '#a855f7',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"Kim helped me go from overwhelmed founder to confident CEO. Our company revenue doubled in 6 months after implementing her frameworks."',
          author: 'Sarah Mitchell',
          role: 'CEO, GrowthLab',
          avatar: '',
          backgroundColor: '#f3e8ff',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Ready to transform your leadership?',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#1e1b4b',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 10 },
      },
      {
        id: generateId(),
        type: 'contact-form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: true,
          showMessage: true,
          nameLabel: 'Name',
          emailLabel: 'Email',
          phoneLabel: 'Phone',
          messageLabel: 'What are you looking for?',
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@company.com',
          phonePlaceholder: '+1 (555) 000-0000',
          messagePlaceholder: 'Tell me about your goals and challenges...',
          buttonText: 'Book My Free Call →',
          buttonColor: '#a855f7',
          successMessage: "Thanks! I'll reach out within 24 hours to schedule your call.",
          requirePhone: false,
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'Coach Kim',
          logoImage: '',
          tagline: 'Empowering leaders to thrive.',
          columns: [],
          socials: [
            { platform: 'linkedin', url: '#', enabled: true },
            { platform: 'instagram', url: '#', enabled: true },
            { platform: 'youtube', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Coach Kim. All rights reserved.',
          style: 'minimal',
          backgroundColor: '#1e1b4b',
          textColor: '#a5b4fc',
          showSocials: true,
        },
      },
    ],
  },
  {
    id: 'restaurant',
    name: 'Restaurant / Café',
    description: 'Elegant restaurant page with menu highlights and reservations',
    thumbnail: '/placeholder.svg',
    requiredPlan: 'business',
    settings: {
      backgroundType: 'solid',
      backgroundColor: '#1a1205',
      primaryColor: '#d97706',
    },
    blocks: [
      {
        id: generateId(),
        type: 'nav',
        props: {
          logoType: 'text',
          logoText: 'SAVEUR',
          logoImage: '',
          menuItems: [
            { id: '1', label: 'Menu', url: '#menu' },
            { id: '2', label: 'About', url: '#about' },
            { id: '3', label: 'Reviews', url: '#reviews' },
          ],
          ctaButton: { enabled: true, text: 'Reserve a Table', url: '#reserve' },
          style: 'transparent',
          alignment: 'spread',
          sticky: true,
          backgroundColor: 'transparent',
          textColor: '#fef3c7',
        },
      },
      {
        id: generateId(),
        type: 'hero',
        props: {
          headline: 'A culinary experience like no other',
          subheadline: 'Modern French cuisine crafted with locally sourced, seasonal ingredients. Reservations now open for spring tasting menu.',
          buttonText: 'Reserve Your Table',
          buttonLink: '#reserve',
          backgroundImage: '',
          backgroundOverlay: 0.4,
          height: 'large',
          alignment: 'center',
          textColor: 'light',
        },
      },
      {
        id: generateId(),
        type: 'image',
        props: {
          src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop',
          alt: 'Restaurant interior - replace with your photo',
          width: 700,
          height: 350,
          alignment: 'center',
          borderRadius: 12,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Our Signature Dishes',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#fef3c7',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'feature-grid',
        props: {
          features: [
            { id: '1', icon: 'Flame', title: 'Wagyu Tartare', description: 'A5 Japanese wagyu, quail egg yolk, truffle vinaigrette, crispy shallots' },
            { id: '2', icon: 'Leaf', title: 'Garden Risotto', description: 'Carnaroli rice, spring vegetables, Parmigiano-Reggiano, herb oil' },
            { id: '3', icon: 'Fish', title: 'Pan-Seared Branzino', description: 'Mediterranean sea bass, saffron beurre blanc, roasted fennel' },
            { id: '4', icon: 'Cherry', title: 'Dark Chocolate Soufflé', description: 'Valrhona chocolate, crème anglaise, candied orange zest' },
          ],
          columns: 2,
          style: 'cards',
          iconColor: '#d97706',
          showIcons: true,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'stats',
        props: {
          stats: [
            { id: '1', value: '⭐ 4.9', label: 'Google Rating' },
            { id: '2', value: '12', label: 'Years Open' },
            { id: '3', value: '1', label: 'Michelin Star' },
          ],
          columns: 3,
          style: 'minimal',
          valueColor: '#d97706',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'testimonial',
        props: {
          quote: '"An unforgettable dining experience. Every dish tells a story. The tasting menu with wine pairing is an absolute must."',
          author: 'Food & Wine Magazine',
          role: 'Editor\'s Pick 2025',
          avatar: '',
          backgroundColor: '#292013',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 60 },
      },
      {
        id: generateId(),
        type: 'heading',
        props: {
          text: 'Make a Reservation',
          level: 'h2',
          fontSize: 36,
          fontWeight: 'bold',
          alignment: 'center',
          color: '#fef3c7',
        },
      },
      {
        id: generateId(),
        type: 'text',
        props: {
          text: 'Join us for an evening of exceptional food and warm hospitality.',
          fontSize: 18,
          alignment: 'center',
          color: '#a1a1aa',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'contact-form',
        props: {
          showName: true,
          showEmail: true,
          showPhone: true,
          showMessage: true,
          nameLabel: 'Name',
          emailLabel: 'Email',
          phoneLabel: 'Phone',
          messageLabel: 'Special requests',
          namePlaceholder: 'Your name',
          emailPlaceholder: 'you@email.com',
          phonePlaceholder: '+1 (555) 000-0000',
          messagePlaceholder: 'Party size, preferred date/time, dietary requirements...',
          buttonText: 'Request Reservation →',
          buttonColor: '#d97706',
          successMessage: "Thank you! We'll confirm your reservation shortly.",
          requirePhone: true,
          layout: 'stacked',
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: generateId(),
        type: 'map',
        props: {
          address: '123 Gourmet Street, San Francisco, CA',
          zoom: 15,
          height: 300,
        },
      },
      {
        id: generateId(),
        type: 'spacer',
        props: { height: 40 },
      },
      {
        id: generateId(),
        type: 'footer',
        props: {
          logoType: 'text',
          logoText: 'SAVEUR',
          logoImage: '',
          tagline: 'Modern French cuisine in the heart of San Francisco.',
          columns: [],
          socials: [
            { platform: 'instagram', url: '#', enabled: true },
            { platform: 'facebook', url: '#', enabled: true },
          ],
          copyrightText: '© 2025 Saveur Restaurant.',
          style: 'minimal',
          backgroundColor: '#1a1205',
          textColor: '#92805a',
          showSocials: true,
        },
      },
    ],
  },
];
